name: Game Bot Xin 15m

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: # Cho phép bấm chạy thủ công để test

jobs:
  run-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Cấp quyền ghi file chống spam
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'GameBot Xin'
          git config --global user.email 'bot@github.com'
          git add sent_games.txt
          git commit -m "Update sent list [skip ci]" || exit 0
          git push
